repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        always_run: true
        pass_filenames: false
      - id: generate passthrough modules
        name: generate passthrough modules
        entry: python scripts/generate_version_submodule_imports.py generate
        language: system
        always_run: true
        pass_filenames: false
