repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.287
    pass_filenames: true
    files: ^.*\.py$
    hooks:
      - id: ruff
        # args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    pass_filenames: true
    files: ^.*\.py$
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        always_run: true
        pass_filenames: true
        files: ^.*\.py$
      - id: generate passthrough modules
        name: generate passthrough modules
        entry: python scripts/generate_version_submodule_imports.py generate
        language: system
        always_run: true
        pass_filenames: false
      - id: generate json schemas
        name: generate json modules
        entry: python scripts/generate_json_schemas.py
        language: system
        always_run: true
        pass_filenames: false
