[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.pyright]
include = ["bioimageio", "scripts", "tests"]
exclude = ["**/node_modules", "**/__pycache__", "tests/old_*"]
typeCheckingMode = "strict"
reportMissingSuperCall = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportUninitializedInstanceVariable = "error"
reportUnknownMemberType = false
reportIncompatibleMethodOverride = true
reportMissingTypeArgument = true
reportMissingTypeStubs = "warning"
useLibraryCodeForTypes = true
reportUnusedCallResult = "error"
reportUnusedVariable = "error"
pythonVersion = "3.9"
pythonPlatform = "All"

[tool.pytest.ini_options]
addopts = "-s --doctest-modules"
testpaths = ["bioimageio", "scripts", "example_specs"]
