[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
preview = true

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "tests/old_*", "tests/cache"]
include = ["bioimageio", "scripts", "tests"]
pythonPlatform = "All"
pythonVersion = "3.8"
reportImportCycles = true
reportIncompatibleMethodOverride = true
reportMissingSuperCall = "error"
reportMissingTypeArgument = true
reportMissingTypeStubs = "warning"
reportPropertyTypeMismatch = true
reportUninitializedInstanceVariable = "error"
reportUnknownMemberType = false
reportUnnecessaryIsInstance = false
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"
reportUnusedImport = "error"
reportUnusedVariable = "error"
strictDictionaryInference = true
strictListInference = true
strictSetInference = true
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
addopts = "-n auto --capture=no --doctest-modules --failed-first"
testpaths = ["bioimageio/spec", "tests", "scripts"]

[tool.ruff]
line-length = 88
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
target-version = "py38"
