[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']

[tool.isort]
line_length = 120
profile = "black"
# sort_reexports = true  # buggy

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "tests/old_*"]
include = ["bioimageio", "scripts", "tests"]
pythonPlatform = "All"
pythonVersion = "3.9"
reportIncompatibleMethodOverride = true
reportMissingSuperCall = "error"
reportMissingTypeArgument = true
reportMissingTypeStubs = "warning"
reportUninitializedInstanceVariable = "error"
reportUnknownMemberType = false
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"
reportUnusedVariable = "error"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

[tool.pytest.ini_options]
addopts = "--capture=no --doctest-modules --failed-first"
testpaths = ["tests", "bioimageio", "scripts", "example_specs"]
