{% set setup_py_data = load_setup_py_data() %}

package:
  name: bioimageio.spec
  version: {{ setup_py_data['version'] }}

source:
  path: ..

requirements:
  build:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.replace(";platform_system!='Emscripten'", "").lower() }}
    {% endfor %}


build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bioimageio.spec
  source_files:
    - tests
    - example_specs
  requires:
    {% for dep in setup_py_data['extras_require']['test'] %}
    - {{ dep.replace('torch', 'pytorch').lower() }}
    {% endfor %}
  commands:
    - pytest .

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: bioimage.io specifications package
  license: MIT
  license_file: LICENSE
